/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id 'com.android.application'
    id 'jacoco'
    id 'aaosApps.buildLogic'
}

android {
    namespace "com.android.car.messenger"

    defaultConfig {
        applicationId "com.android.car.messenger"
        minSdkVersion 31
        targetSdkVersion 34
        testInstrumentationRunnerArguments clearPackageData: 'true', coverage: 'true'
    }

    lintOptions {
        abortOnError false
    }

    signingConfigs {
        unbundled {
            storeFile file(gradle.ext.unbundledCertPath)
            storePassword 'carapps'
            keyAlias 'carapps'
            keyPassword 'carapps'
        }
    }

    project.gradle.taskGraph.whenReady {
        connectedFakeDebugAndroidTest {
            ignoreFailures = true
        }
    }

    flavorDimensions 'devMode'
    productFlavors {
        prod {
            dimension 'devMode'
            signingConfig signingConfigs.unbundled
        }

        fake {
            dimension 'devMode'
            versionNameSuffix '-fake'
            testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
            signingConfig signingConfigs.unbundled
        }
    }

    buildTypes {
        debug {
            testCoverageEnabled true
            signingConfig android.buildTypes.release.signingConfig
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            res.srcDirs = ['res']
        }

        androidTestFake {
            setRoot('tests')
            java.srcDirs = ['tests/src']
        }
    }

    testOptions {
        animationsDisabled true
    }

    // Disable release build for fake build
    variantFilter { variant ->
        def names = variant.flavors*.name
        if (variant.buildType.name == 'release') {
            if (names.contains('fake')) {
                setIgnore(true)
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation files(gradle.ext.lib_car_system_stubs)

    implementation libs.androidx.constraintlayout

    implementation libs.androidx.lifecycle.common.java8


    implementation libs.androidx.preference
    implementation libs.androidx.annotation

    implementation project(':car-apps-common')
    implementation project(':car-assist-lib')
    implementation project(':car-messenger-common')
    implementation project(':car-messenger-common:model')
    implementation project(':car-ui-lib')
    implementation project(':car-telephony-common')

    fakeImplementation libs.dexmaker.mockito.inline.extended
    fakeImplementation project(path: ":car-messenger-app:testing")

    androidTestImplementation(libs.androidx.espresso.core) {
        exclude group: 'org.checkerframework', module: 'checker'
    }
    androidTestImplementation(libs.androidx.espresso.contrib) {
        exclude group: 'org.checkerframework', module: 'checker'
    }
    androidTestImplementation(libs.androidx.espresso.intents) {
        exclude group: 'org.checkerframework', module: 'checker'
    }
    androidTestImplementation libs.hamcrest
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.test.core
    androidTestImplementation libs.androidx.test.rules
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.google.truth
    androidTestImplementation libs.dexmaker.mockito.inline.extended
    androidTestImplementation project(':car-testing-common')
    androidTestImplementation libs.androidx.arch.core.testing
}
